#!/bin/sh

echo
echo "1. Search for vagrant logs for: 'This VM has IP address'"
echo
echo "2. SSH into the vagrant box: vagrant ssh"
echo
echo "3. Copy the kubeconfig to the local filesystem: cp /home/vagrant/.kube/config /vagrant/kubeconfig"
echo
echo "4. Modify the server IP address of the kubeconfig file"
echo
echo "5. export KUBECONFIG=$PWD/kubeconfig"
echo
echo "6. Test with: kubectl get nodes -n kube-system"

exit 0

# Add pod networking add-on

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

# Allow pods to run on this master node

kubectl taint nodes --all node-role.kubernetes.io/master-

# install Helm

kubectl -n kube-system create sa tiller \
    && kubectl create clusterrolebinding tiller
       --clusterrole cluster-admin
       --serviceaccount=kube-system:tiller

helm init --skip-refresh --upgrade --service-account tiller

# Watch when pod is running
kubectl get pods -n kube-system
